stages:
  - build

variables:
  DOCKER_DRIVER: overlay2


build-cross-platform:
  stage: build
  image: docker:24-cli
  services:
   - name: docker:24-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker context create ci
    - docker buildx create --name multiarch-builder --driver docker-container --use ci
    - docker buildx inspect --bootstrap
  script:
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        TAG="$CI_COMMIT_TAG"
      else
        TAG=$(echo $CI_COMMIT_SHORT_SHA)
      fi
      docker buildx build \
        --provenance=false \
        --cache-from type=registry,ref=${CI_REGISTRY_IMAGE}:buildcache \
        --cache-to type=registry,ref=${CI_REGISTRY_IMAGE}:buildcache,mode=max \
        --push --platform  linux/amd64,linux/arm64 \
        --tag $CI_REGISTRY_IMAGE:$TAG \
        .
  after_script:
    - docker buildx rm multiarch-builder || true
  rules:
    - if: '$CI_COMMIT_TAG'
      when: always
    - if: '$CI_COMMIT_BRANCH'
      when: manual