stages: [build]

variables:
  IMAGE_TAG: ${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}

buildx-publish:
  stage: build
  image: docker:24-cli
  services:
    - name: docker:24-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker context create build || true
    - docker run --privileged --rm tonistiigi/binfmt --install all
    - docker buildx create build --use --name multiarch --driver docker-container
    - docker buildx inspect --bootstrap
  script:
    - |
#      if [ -n "$CI_COMMIT_TAG" ]; then
#        TAG="$CI_COMMIT_TAG"
#      else
#        TAG=$(echo $CI_COMMIT_SHORT_SHA)
#      fi
    - docker buildx build \
      --platform linux/amd64,linux/arm64 \
      --pull \
      --tag "${CI_REGISTRY_IMAGE}:${IMAGE_TAG}" \
      --push \
      .
    - docker buildx imagetools inspect "${CI_REGISTRY_IMAGE}:${IMAGE_TAG}"
  after_script:
    - docker buildx rm multiarch || true
  rules:
    - if: '$CI_COMMIT_TAG'
      when: always
    - if: '$CI_COMMIT_BRANCH'
      when: manual



