services:
  postgres:

    image: postgres:16.9-alpine
    ports:
      - "5432:5432"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network


  todo-app:
    image: registry.csc.sibsutis.ru/is341s29/arp_chudov_is341s29:v1.0
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    links:
      - postgres:postgres

volumes:
  db_data:

networks:
  app-network:
    driver: bridge